-- print(SharedUtils:GetLevelName())
local mounted = false
-- Events:Subscribe(
--     "BundleMounter:GetBundles",
--     function(bundles)
--         print(SharedUtils:GetLevelName())
--         name = SharedUtils:GetLevelName()
--         if name ~= "Levels/MP_012/MP_012" and name ~= nil and mounted == false then
--             print("loading tanks")
--             --Events:Dispatch(
--             ---    "BundleMounter:LoadBundles",
--             --    "Levels/MP_012/MP_012",
--             --    {
--             --        "Levels/MP_012/MP_012",
--              --       "Levels/MP_012/conquest_large"
--             --    }
--             --)
--         end
--     end
-- )
